env:
  TRAVIS: true
cache:
  pip: true

language:
  python

python:
  - "3.6"

dist:
  - "trusty"

before_install:
  - cd api
  - sudo apt-get install -y poppler-utils
  - sudo apt-get install -y ghostscript
  - sudo apt-get install -y imagemagick

install:
  - pip install -e .
  - pip install pytest webtest

script:
  - export TESTENV=travis && pytest tests

services:
  - postgresql

addons:
  postgresql: "9.5"

before_script:
  - pg_config
  - psql -c 'CREATE DATABASE idris;' -U postgres
  - psql -c "CREATE USER idris WITH PASSWORD 'c4l31d0'" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE idris to idris' -U postgres;
  - psql idris -c 'CREATE EXTENSION ltree' -U postgres
  - initialize_db idris-dev.ini
