env:
  TRAVIS: true
cache:
  pip: true

language:
  python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install tox
  - export TOXENV=py${TRAVIS_PYTHON_VERSION//./}

script:
  - tox -e ${TOXENV}

services:
  - postgresql

addons:
  - postgresql: "9.5.10"

before_script:
  - pg_config
  - psql -c 'CREATE DATABASE caleido;' -U postgres
  - psql -c "CREATE USER caleido WITH PASSWORD 'c4l31d0'" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE caleido to caleido' -U postgres;
  - psql caleido -c 'CREATE EXTENSION ltree' -U postgres
  - initialize_db caleido.ini
