cache:
  pip: true

language:
  python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox
  - export TOXENV=py${TRAVIS_PYTHON_VERSION//./}

script:
  - tox -e ${TOXENV}

services:
  - postgresql

addons:
  - postgresql: "9.5"

before_script:
  - psql -c 'CREATE DATABASE caleido;' -U postgres
  - psql -c "CREATE USER caleido WITH PASSWORD 'c4l31d0'" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE caleido to caleido' -U postgres;
  - initialize_db caleido.ini