runtime: python
env: flex
entrypoint: gunicorn --paste caleido.ini -b :$PORT

runtime_config:
  python_version: 3

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: caleido-eur:europe-west1:caleidev
#[END cloudsql_settings]
