runtime: custom
env: flex
entrypoint: gunicorn --paste idris-gae.ini -b :$PORT

runtime_config:
  python_version: 3

beta_settings:
    cloud_sql_instances: caleido-eur:europe-west1:caleidev

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
