runtime: custom
env: flex

beta_settings:
    cloud_sql_instances: caleido-eur:europe-west1:caleidev

liveness_check:
  path: "/check/live"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/check/ready"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

skip_files:
  - ^lib/.*
  - ^var/.*

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
